apiVersion: v1
kind: ReplicationController
metadata:
  name:  myjavaapp-rc
spec:
  replicas: 2
  selector:
    app:  myjavaapp
    version: 1.0.1
  template:
    metadata:
      name:  myjavaapp
      labels:
        app:  myjavaapp
        version: 1.0.1
    spec:
      containers:
        - name:  myjavaapp
          image: maha4iac/mymahalogin:1
          ports:
            - containerPort: 8080