apiVersion: v1
kind: ReplicationController
metadata:
    name: mahi-rc
spec:
  replicas: 2
  selector:
    app: mahiapp
  template:
    metadata:
      labels:
        app: mahiapp
    spec:
      containers:
      - name: mahi-container
        image: mahi07nayak/myjava:1
        ports:
        - containerPort: 8080