apiVersion: v1
kind: Replication controller
metadata:
  name: "mahiRC"
spec:
  replicas: 2
  selector:
    app: mahijavaapp
  template: 
    metadata:
    labels:
      app: mahijavaapp
    spec:
     containers:
     - name: mahi-java-container
       image: maha4iac/myjava:1
       ports:
       - containerport: 8080