apiVersion: v1
kind: ReplicationController
metadata:
    name: nginx-rc
Spec:
  replicas: 2
  selector:
    app: nginxapp
  template:
    metadata:
      labels:
        app: nginxapp
    Spec:
     containers:
     - name: nginx-container
       image: nginx
       ports:
       - containerport: 8080