apiVersion: v1
kind: replication controller
metadata: 
  name: maha-rc
spec:
  replicas: 2
  selector:
    app: mahajavaapp
  template: 
    metadata:
    labels:
      app: mahajavaapp
    spec:
     containers:
     - name: maha-java-container
       image: maha4iac/myjava:1
       ports:
       - containerport: 8080