apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp-deploy
  labels:
    app: javaapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
        - name: myjavaapp-container
          image: maha4iac/myonlinebooking:2
          ports:
            - containerPort: 8080 