apiVersion: v1
kind: Service
metadata:
  name: mahi-svc
  labels:
    app: myjavaapp
spec:
  selector:
    app: myjavaapp
  type: NodePort
  ports:
    - port: 8080
      nodeport: 30001
      protocol: TCP
    

 
